### ISSUE TITLE
Notice and Warning with latest WP version

### ISSUE THREAD

**Issue by plueschpruem** [mcguffin/wp-unique-media#8]
The PlugIn works great - thanks a lot!

But query monitor throws two errors:
-1-:
`Notice – Undefined property: UniqueMedia\Core\Core::$_version – wp-content/plugins/wp-unique-media/include/UniqueMedia/Core/Plugin.php:93`
changing line 93 to this solves it for me:
`if (!isset( $this->_version ) || is_null( $this->_version ) ) { […]`
Basically added !isset() [note the ! / not]

-2-:
`Warning (Suppressed) | Invalid callback UniqueMedia\Core\Core::__wakeup, cannot access private method UniqueMedia\Core\Core::__wakeup()`
Trace for -2-:
```
wp-includes/functions.php:594
unserialize()
wp-includes/functions.php:594
maybe_unserialize()
wp-includes/option.php:178
get_option()
wp-includes/option.php:563
add_option()
wp-content/plugins/wp-unique-media/include/UniqueMedia/Cron/Cron.php:118
UniqueMedia\C\Cron->__construct()
wp-content/plugins/wp-unique-media/include/UniqueMedia/Core/Singleton.php:33
UniqueMedia\C\Singleton::instance()
wp-content/plugins/wp-unique-media/index.php:53
```

Not sure about this one, PHP classes are not my strong suit…

(latest WP, PHP 7.4.10)

**Comment by 1ucay** [comment]
Hi, I have same error.
